In [1]:
import pandas as pd
import numpy as np

# 1.1 Numpy array

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14 , 3, 4]

[3.14, 3, 4]

In [4]:
np.array([3.14 , 3, 4]) #sẽ chuyển tất cả về dạng float nếu sử dụng hàm trong numpy

array([3.14, 3.  , 4.  ])

In [5]:
np.array([3.14 , 3, 4], dtype = 'float32')

array([3.14, 3.  , 4.  ], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3,4],[4,5,6,7]])
type(a2)

numpy.ndarray

In [8]:
a2.shape #xem số cột, số dòng của array

(2, 4)

In [9]:
a2.ndim

2

In [10]:
a2.dtype

dtype('int32')

In [11]:
a2.size

8

# 1.2 Numpy array from Scratch (zeros, ones, full, arange, linspace)


In [12]:
np.zeros([2,4], dtype = int) #bảng 2 chiều - sẽ tạo ra số 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones((3,5),dtype=float) #bảng 2 chiều - sẽ tạo ra số 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 1.3 Random

In [17]:
np.random.random((4,4))

array([[0.57497051, 0.40066113, 0.94463958, 0.95238404],
       [0.11115281, 0.97997982, 0.53421182, 0.06348118],
       [0.75088284, 0.04703477, 0.19970423, 0.00140796],
       [0.08733889, 0.81364141, 0.7746278 , 0.37495747]])

In [18]:
np.random.random((4))

array([0.0294879 , 0.06682303, 0.07102691, 0.32011439])

In [19]:
#không thay đổi hàm ngẫu nhiên mỗi lần chạy và giống nhau giữa các máy
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [20]:
np.random.normal(0,1,(3,3)) #tạo ra array có phân phối chuẩn

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [21]:
np.random.randint(0,10,(4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [22]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

# 1.4 Array Indexing & Slicing

# One-dimensional subarray

In [23]:
x1 = np.random.randint(0,20, size =6)
x1

array([15, 13, 16, 17,  5,  9])

In [24]:
x1[4], x1[0], x1[-1] #-1 là vị trí cuối cùng

(5, 15, 9)

# Multi-dimensional subarray

In [25]:
x2 = np.random.randint(10, size =(3,4))

In [26]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [27]:
x2[1,0] #tìm giá trị tại vị trí đó

1

In [28]:
x2[1,2] = 5 #thay đổi dữ liệu của 1 vị trí mà mình muốn

In [29]:
x2

array([[3, 0, 5, 0],
       [1, 2, 5, 2],
       [0, 3, 2, 0]])

# Slicing

In [30]:
x1

array([15, 13, 16, 17,  5,  9])

In [31]:
x1[0:3]

array([15, 13, 16])

In [32]:
x1[2:4]

array([16, 17])

In [33]:
x1[::2]

array([15, 16,  5])

In [34]:
x1[1::2]

array([13, 17,  9])

In [35]:
x2

array([[3, 0, 5, 0],
       [1, 2, 5, 2],
       [0, 3, 2, 0]])

In [36]:
x2[0:2,0:3] #hàng - cột

array([[3, 0, 5],
       [1, 2, 5]])

In [37]:
x2[:,:2]

array([[3, 0],
       [1, 2],
       [0, 3]])

# 1.5 Reshape of arrays & Transpose (T)

In [38]:
grid =np.arange(1,10)

In [39]:
grid.shape

(9,)

In [40]:
grid.reshape((3,3)) #thay đổi cấu trúc của array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
x = np.array([1,2,3])
x.shape

(3,)

In [42]:
x.reshape((1,3)).shape

(1, 3)

In [43]:
x3= np.array([[1.,2.],[3.,4.]])

In [44]:
x3

array([[1., 2.],
       [3., 4.]])

In [45]:
x.T #thay đổi thứ tự cột thành dòng và dòng thành cột

array([1, 2, 3])

# 1.6 Concatenate & Split

Concatenate

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [47]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [48]:
x2chieu = np.array([[1,2,3],[4,5,6]])

In [49]:
x2chieu

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate((x2chieu,x2chieu)) #axis = 0 mặc định nối theo chiều ngang

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate((x2chieu,x2chieu), axis =1) #để axis =1 vào để nối theo chiều dọc 2 cái array 2 chiều với nhau

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x10 = np.array([1,2,3])
grid2 = np.array([[7,8,9],[4,5,6]])
grid3 =np.array([[99],[99]])

In [53]:
np.vstack((x10,grid2)) #vertical

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [54]:
np.hstack((grid2,grid3)) #horizontal nhưng phải đúng mới ghép được, vì ghép theo hàng

array([[ 7,  8,  9, 99],
       [ 4,  5,  6, 99]])

Split

In [55]:
c = np.array([1,2,3,99,69,3,2,1])

In [56]:
c1, c2, c3=np.split(c, [3,5])


In [57]:
np.split(c, [2,5])

[array([1, 2]), array([ 3, 99, 69]), array([3, 2, 1])]

In [58]:
c1

array([1, 2, 3])

In [59]:
c2

array([99, 69])

In [60]:
c3

array([3, 2, 1])

# 1.7 Broadcasting & Vectorized operations

In [61]:
a1 = np.arange(3)

In [62]:
a1

array([0, 1, 2])

In [63]:
a +5 #cùng size và cộng vào tất cả giá trị trong array đó

array([6, 7, 8])

In [64]:
b1=np.ones((3,3))

In [65]:
b1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a1.shape, b1.shape

((3,), (3, 3))

In [67]:
a1+b1

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [68]:
a2 =np.arange(3).reshape(3,1)

In [69]:
a2

array([[0],
       [1],
       [2]])

In [70]:
a1+a2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 1.8 Manipulating & Comparing array

Link: https://www.youtube.com/watch?v=1eSmR2EJjYM&t=43s

# 1.9 Sorting

In [83]:
q = np.array([8,6,4,3,1,2,5])

In [84]:
np.sort(q)

array([1, 2, 3, 4, 5, 6, 8])

In [85]:
np.argsort(q) #vị trí của các giá trị khi mà sort

array([4, 5, 3, 2, 6, 1, 0], dtype=int64)

Sorting along rows and columns

In [90]:
np.random.seed(42)

In [91]:
MatA= np.random.randint(0,10,size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [92]:
np.sort(MatA, axis = 0) #sắp xếp theo chiều dọc

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [93]:
np.sort(MatA, axis = 1) #sắp xếp theo chiều ngang

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# 2.0 Dot Product Example

In [95]:
np.random.seed(0)

In [96]:
sale=np.random.randint(0,20,size =(5,3))

In [97]:
sale

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [102]:
weekysale=pd.DataFrame(sale, index = ['Mon','Tue', 'WEd','Thurs','Fri'],
                       columns=['Almond Butter','Peanut Butter','Cashew Butter'])

In [103]:
weekysale

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
WEd                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [104]:
prices = np.array([10,8,12])

In [106]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['price'],columns =['Almond Butter','Peanut Butter','Cashew Butter'])

In [107]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
price             10              8             12

In [108]:
weekysale.shape,butter_prices.shape

((5, 3), (1, 3))

In [110]:
total = weekysale.dot(butter_prices.T) #phải transpose để có thể nhân được 2 cái shape khác nhau kìa

In [111]:
total

price
Mon      240
Tue      138
WEd      458
Thurs    232
Fri      142

In [112]:
weekysale['Total prices'] =total #thêm cột vào trong Dataframe

In [113]:
weekysale

Almond Butter  Peanut Butter  Cashew Butter  Total prices
Mon               12             15              0           240
Tue                3              3              7           138
WEd                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142